/* Generated By:JavaCC: Do not edit this line. JALPParserConstants.java */
package uk.co.mtford.jalp.abduction.parse.program;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JALPParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACKET = 6;
  /** RegularExpression Id. */
  int RBRACKET = 7;
  /** RegularExpression Id. */
  int DEFINES = 8;
  /** RegularExpression Id. */
  int COMMA = 9;
  /** RegularExpression Id. */
  int DOT = 10;
  /** RegularExpression Id. */
  int EQUALS = 11;
  /** RegularExpression Id. */
  int NOTEQUALS = 12;
  /** RegularExpression Id. */
  int LESSTHAN = 13;
  /** RegularExpression Id. */
  int LESSTHANEQ = 14;
  /** RegularExpression Id. */
  int GREATERTHAN = 15;
  /** RegularExpression Id. */
  int GREATERTHANEQ = 16;
  /** RegularExpression Id. */
  int LSQBRACKET = 17;
  /** RegularExpression Id. */
  int RSQBRACKET = 18;
  /** RegularExpression Id. */
  int NOT = 19;
  /** RegularExpression Id. */
  int IC = 20;
  /** RegularExpression Id. */
  int IN = 21;
  /** RegularExpression Id. */
  int FSLASH = 22;
  /** RegularExpression Id. */
  int ABDUCIBLE = 23;
  /** RegularExpression Id. */
  int INTEGER = 24;
  /** RegularExpression Id. */
  int LCASENAME = 25;
  /** RegularExpression Id. */
  int UCASENAME = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "\"(\"",
    "\")\"",
    "\":-\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"[\"",
    "\"]\"",
    "\"not\"",
    "\"ic\"",
    "\"in\"",
    "\"/\"",
    "\"abducible\"",
    "<INTEGER>",
    "<LCASENAME>",
    "<UCASENAME>",
  };

}
