/* Generated By:JavaCC: Do not edit this line. ALPParserConstants.java */
package uk.co.mtford.alp.abduction.parse.program;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ALPParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACKET = 5;
  /** RegularExpression Id. */
  int RBRACKET = 6;
  /** RegularExpression Id. */
  int DEFINES = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int DOT = 9;
  /** RegularExpression Id. */
  int EQUALS = 10;
  /** RegularExpression Id. */
  int NOT = 11;
  /** RegularExpression Id. */
  int IC = 12;
  /** RegularExpression Id. */
  int ABDUCIBLE = 13;
  /** RegularExpression Id. */
  int LCASENAME = 14;
  /** RegularExpression Id. */
  int UCASENAME = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\":-\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"not\"",
    "\"ic\"",
    "\"abducible\"",
    "<LCASENAME>",
    "<UCASENAME>",
  };

}
