/* Generated By:JavaCC: Do not edit this line. JALPQueryParserConstants.java */
package uk.co.mtford.jalp.abduction.parse.query;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JALPQueryParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACKET = 5;
  /** RegularExpression Id. */
  int RBRACKET = 6;
  /** RegularExpression Id. */
  int COMMA = 7;
  /** RegularExpression Id. */
  int INTEGER = 8;
  /** RegularExpression Id. */
  int LCASENAME = 9;
  /** RegularExpression Id. */
  int UCASENAME = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<INTEGER>",
    "<LCASENAME>",
    "<UCASENAME>",
  };

}
